from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


PAGE = r"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#EFDFD1"><title>type//race — Type fast. Stay sharp.</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap');
    :root{--bg:#10110f;--panel:#171916;--line:#292c27;--muted:#777d73;--text:#e9ece3;--lime:#c5f36b;--orange:#f3a66b;--mono:'DM Mono',monospace;--sans:'Manrope',sans-serif}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:var(--sans);min-height:100vh}button{font:inherit;color:inherit}a{color:inherit;text-decoration:none}
    .shell{max-width:1200px;margin:auto;padding:0 44px}.topbar{height:78px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}.brand{font-weight:800;letter-spacing:-1px;font-size:19px}.brand em{font-style:normal;color:var(--lime)}.nav{display:flex;gap:34px;font:12px var(--mono);color:#a6a99f}.nav a{transition:color .2s}.nav a:hover,.nav a.active{color:var(--lime)}.profile{display:flex;align-items:center;gap:10px;font-size:12px;color:#c5c8bd}.avatar{height:32px;width:32px;border-radius:50%;background:#333a29;color:var(--lime);display:grid;place-items:center;font:12px var(--mono);border:1px solid #465333}
    .hero{padding:48px 0 35px;display:flex;align-items:flex-end;justify-content:space-between}.eyebrow{font:11px var(--mono);letter-spacing:1.5px;color:var(--lime);text-transform:uppercase;display:flex;align-items:center;gap:9px}.dot{height:6px;width:6px;border-radius:50%;background:var(--lime);box-shadow:0 0 10px #c5f36b99;animation:pulse 2s infinite}@keyframes pulse{50%{opacity:.35;box-shadow:0 0 2px #c5f36b}}h1{font-size:clamp(38px,5vw,62px);letter-spacing:-3px;line-height:1.04;margin:15px 0 8px;font-weight:700}h1 span{color:var(--lime)}.sub{color:var(--muted);font-size:13px}.daily{border:1px solid var(--line);background:#151713;padding:13px 17px;border-radius:8px;font:11px var(--mono);color:#a4a89a}.daily b{color:var(--lime);font-weight:400;margin-left:8px}
    .race{border:1px solid #30342c;background:var(--panel);border-radius:12px;overflow:hidden;box-shadow:0 20px 70px #0003}.race-head{height:58px;padding:0 22px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}.race-meta{display:flex;gap:24px;align-items:center;color:var(--muted);font:11px var(--mono)}.race-meta strong{font-weight:400;color:#d4d8cb}.race-meta .sep{height:15px;width:1px;background:var(--line)}.mode{color:var(--lime);font:11px var(--mono)}.track{padding:24px 24px 18px;border-bottom:1px solid var(--line);position:relative}.track-label{display:flex;justify-content:space-between;font:10px var(--mono);color:var(--muted);margin-bottom:15px}.lanes{display:grid;gap:11px}.lane{height:35px;background:#111310;border:1px solid #252822;border-radius:6px;position:relative;overflow:hidden}.lane::after{content:'';position:absolute;inset:0;background:repeating-linear-gradient(90deg,transparent 0,transparent calc(10% - 1px),#ffffff08 calc(10% - 1px),#ffffff08 10%)}.car{position:absolute;z-index:1;left:var(--pos,0%);top:3px;height:27px;width:42px;border-radius:5px;background:var(--car);display:grid;place-items:center;transition:left .8s cubic-bezier(.2,.8,.2,1);box-shadow:0 0 18px color-mix(in srgb,var(--car),transparent 72%)}.car svg{width:25px;height:18px}.lane.you .car{box-shadow:0 0 20px #c5f36b55}.lane-name{position:absolute;z-index:2;left:10px;top:10px;font:9px var(--mono);color:#ffffffa6}.finish{position:absolute;right:28px;top:40px;bottom:20px;width:3px;background:repeating-linear-gradient(180deg,#c5f36b 0 5px,transparent 5px 9px);opacity:.8}
    .typing{padding:25px 28px 22px;min-width:0}.stats{display:flex;gap:38px;margin-bottom:19px}.stat-label{display:block;color:var(--muted);font:10px var(--mono);letter-spacing:.6px;margin-bottom:5px}.stat-value{font:25px var(--mono);letter-spacing:-1px}.stat-value small{font-size:11px;color:var(--muted);letter-spacing:0}.stat-value.lime{color:var(--lime)}.quote{font:17px/1.9 var(--mono);letter-spacing:.1px;min-height:65px;color:#555b51;user-select:none;overflow-wrap:anywhere;word-break:normal;white-space:normal}.quote .typed{color:#e2e8d7}.quote .current{color:#10110f;background:var(--lime);border-radius:2px;box-shadow:0 0 10px #c5f36b55}.quote .wrong{color:#ff7f70;background:#ff7f7022;text-decoration:underline}.input-row{display:flex;gap:10px;margin-top:17px}.typebox{flex:1;min-width:0;background:#111310;border:1px solid #30342c;border-radius:7px;color:var(--text);padding:14px 16px;font:13px var(--mono);outline:none;transition:border .2s,box-shadow .2s}.typebox:focus{border-color:#8aaa4b;box-shadow:0 0 0 3px #c5f36b12}.typebox::placeholder{color:#5e6459}.btn{flex-shrink:0;border:0;border-radius:7px;padding:0 18px;background:var(--lime);color:#171b10;font:600 12px var(--mono);cursor:pointer;transition:transform .2s,filter .2s}.btn:hover{transform:translateY(-2px);filter:brightness(1.07)}.hint{font:10px var(--mono);color:#666c60;margin-top:11px}.hint kbd{border:1px solid #353930;border-radius:3px;padding:2px 5px;color:#a6ac9e;font:10px var(--mono)}
    .below{display:grid;grid-template-columns:1.15fr .85fr;gap:18px;margin-top:20px;margin-bottom:60px}.card{border:1px solid var(--line);border-radius:10px;background:#151713;padding:19px 21px}.card-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:17px}.card-title h2{font-size:13px;margin:0;font-weight:600}.card-title span{font:10px var(--mono);color:var(--muted)}.leader-row{display:grid;grid-template-columns:28px 1fr 65px 60px;align-items:center;gap:10px;padding:10px 0;border-top:1px solid #242720;font-size:12px}.rank{font:11px var(--mono);color:var(--muted)}.rank.gold{color:#e6c776}.person{display:flex;align-items:center;gap:9px}.mini-avatar{height:25px;width:25px;display:grid;place-items:center;border-radius:50%;background:#2b3027;color:#c3caad;font:9px var(--mono)}.person-name{font-weight:600}.you-tag{font:9px var(--mono);color:var(--lime);margin-left:5px}.wpm,.accuracy{font:11px var(--mono);text-align:right;color:#d4d9ca}.accuracy{color:#858b7e}.leader-row.you-row .person-name,.leader-row.you-row .wpm{color:var(--lime)}.recent{display:flex;flex-direction:column;gap:14px}.recent-item{display:flex;align-items:center;justify-content:space-between}.recent-item+ .recent-item{border-top:1px solid #242720;padding-top:13px}.recent-left{display:flex;align-items:center;gap:10px}.result-icon{height:27px;width:27px;border-radius:6px;background:#252b1e;color:var(--lime);display:grid;place-items:center;font:13px var(--mono)}.result-text strong{font-size:11px;display:block}.result-text small{color:var(--muted);font:9px var(--mono)}.result-score{font:11px var(--mono);color:#d9decf}.toast{position:fixed;bottom:24px;left:50%;transform:translate(-50%,20px);opacity:0;pointer-events:none;background:#252a20;border:1px solid #526039;color:var(--lime);padding:12px 18px;border-radius:8px;font:12px var(--mono);transition:.3s}.toast.show{opacity:1;transform:translate(-50%,0)}footer{border-top:1px solid var(--line);padding:20px 0;color:#656b60;font:10px var(--mono);display:flex;justify-content:space-between}.kbd-hint{color:#90968a}
    .name-dialog{width:min(420px,calc(100% - 32px));border:1px solid #41483a;border-radius:12px;background:#171916;color:var(--text);padding:26px;box-shadow:0 25px 100px #000a}.name-dialog::backdrop{background:#090a08c9;backdrop-filter:blur(5px)}.name-dialog h2{font-size:22px;margin:0 0 8px}.name-dialog p{font:12px var(--mono);color:var(--lime);margin:0 0 19px}.name-dialog label{display:block;font:10px var(--mono);color:var(--muted);margin-bottom:8px}.name-dialog input{width:100%;background:#111310;border:1px solid #30342c;border-radius:7px;color:var(--text);padding:13px;font:13px var(--mono);outline:none}.name-dialog input:focus{border-color:#8aaa4b}.dialog-actions{display:flex;justify-content:flex-end;margin-top:18px}.dialog-actions .btn{height:40px}
    @media(max-width:700px){.shell{padding:0 18px}.nav{gap:15px}.nav a:nth-child(2){display:none}.profile span{display:none}.hero{align-items:flex-start;gap:16px;flex-direction:column}.daily{display:none}.race-head{padding:0 14px}.race-meta{gap:12px}.track{padding:18px 14px}.finish{right:18px}.typing{padding:20px 16px}.stats{gap:22px}.stat-value{font-size:21px}.quote{font-size:14px}.below{grid-template-columns:1fr}.leader-row{grid-template-columns:24px 1fr 52px 48px}.race-meta .sep,.race-meta span:nth-of-type(2){display:none}}
    @media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;transition-duration:.01ms!important;scroll-behavior:auto!important}}
  </style>
  <style>
    :root{--bg:#EFDFD1;--panel:#F8F1EA;--line:#D8C5B5;--muted:#806F62;--text:#332820;--lime:#98613F;--orange:#C47A4D}
    body{background:var(--bg);color:var(--text)}
    .topbar,.race-head,.track,.card,footer{border-color:var(--line)}
    .nav,.profile,.race-meta strong,.person-name,.result-text strong{color:#54453B}
    .avatar,.mini-avatar{background:#E6D2C1;color:#754A32;border-color:#C9A98E}
    .daily,.race,.card,.name-dialog{background:var(--panel)}
    .race{border-color:var(--line);box-shadow:0 20px 70px #6F4D3320}
    .race-meta strong{color:var(--text)}
    .lane{background:#EFE3D7;border-color:#D9C6B5}
    .lane::after{background:repeating-linear-gradient(90deg,transparent 0,transparent calc(10% - 1px),#765A4314 calc(10% - 1px),#765A4314 10%)}
    .lane-name{color:#705D4F}.lane.you .car{box-shadow:0 0 20px #98613F55}
    .finish{background:repeating-linear-gradient(180deg,var(--lime) 0 5px,transparent 5px 9px)}
    .quote{color:#8A7868}.quote .typed{color:#44352B}.quote .current{color:#FFF8F1;background:var(--lime);box-shadow:0 0 10px #98613F55}.quote .wrong{color:#A63E35;background:#A63E3518}
    .typebox,.name-dialog input{background:#FFF9F3;border-color:var(--line);color:var(--text)}
    .typebox::placeholder{color:#8A7868}.typebox:focus,.name-dialog input:focus{border-color:var(--lime);box-shadow:0 0 0 3px #98613F18}
    .btn{background:var(--lime);color:#FFF8F1}.hint{color:#806F62}.hint kbd{border-color:var(--line);color:#6E5D50}
    .leader-row,.recent-item+.recent-item{border-color:#E6D9CD}.rank.gold{color:#A06B39}.wpm,.result-score{color:#493A30}.accuracy,.result-text small,.card-title span{color:var(--muted)}
    .result-icon{background:#EDE0D3;color:var(--lime)}.toast{background:#4A382C;border-color:#926444;color:#F5EADF}
    .name-dialog{border-color:#D8C5B5;color:var(--text);box-shadow:0 25px 100px #6F4D3333}.name-dialog::backdrop{background:#47372B66;backdrop-filter:blur(5px)}.name-dialog p{color:var(--lime)}.name-dialog label{color:var(--muted)}
    footer{color:#806F62}
  </style>
</head>
<body><div class="shell">
  <header class="topbar"><a class="brand" href="#">type<em>//</em>race</a><nav class="nav"><a class="active" href="#race">Race</a><a href="#leaderboard">Leaderboard</a><a href="#history">History</a></nav><div class="profile"><div class="avatar" id="profileAvatar">Y</div><span id="playerLabel">You · Guest</span></div></header>
  <section class="hero"><div><div class="eyebrow"><i class="dot"></i> SOLO RUN · <span id="dateLabel">TODAY</span></div><h1>Find your <span>flow.</span></h1><div class="sub">One minute. A few good words. See where you land.</div></div><div class="daily">YOUR PERSONAL BEST <b id="personalBest">—</b></div></section>
  <main id="race" class="race"><div class="race-head"><div class="race-meta"><span>MODE <strong>SOLO</strong></span><i class="sep"></i><span>PLAYERS <strong>1</strong></span><i class="sep"></i><span>TIME <strong>60 SEC</strong></span></div><span class="mode">● SOLO RUN</span></div>
    <section class="track"><div class="track-label"><span>START</span><span>FINISH</span></div><div class="lanes" id="lanes"></div><div class="finish"></div></section>
    <section class="typing"><div class="stats"><div><span class="stat-label">YOUR SPEED</span><div class="stat-value lime" id="wpm">0 <small>WPM</small></div></div><div><span class="stat-label">ACCURACY</span><div class="stat-value" id="accuracy">100<small>%</small></div></div><div><span class="stat-label">TIME LEFT</span><div class="stat-value" id="time">60<small>s</small></div></div></div>
      <div class="quote" id="quote" aria-live="polite"></div><div class="input-row"><input class="typebox" id="typebox" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="Click here and start typing to join the race…"><button class="btn" id="restart">↻ &nbsp;Restart</button></div><div class="hint"><kbd>Tab</kbd> + <kbd>Enter</kbd> to restart <span style="margin-left:12px">·</span><span style="margin-left:12px">Your car moves as you type</span></div>
    </section></main>
  <section class="below"><article class="card" id="leaderboard"><div class="card-title"><h2>Solo leaderboard</h2><span>TOP 10 · THIS DEVICE</span></div><div id="leaderRows"></div></article><article class="card" id="history"><div class="card-title"><h2>Recent runs</h2><span>LAST 3</span></div><div class="recent" id="recent"></div></article></section>
  <footer><span>type//race © 2025</span><span class="kbd-hint">A little practice goes a long way.</span></footer>
</div><div class="toast" id="toast"></div>
<dialog class="name-dialog" id="nameDialog"><form id="scoreForm"><h2>Run complete.</h2><p class="score-summary" id="scoreSummary"></p><label for="playerName">ADD YOUR NAME TO THE LEADERBOARD</label><input id="playerName" name="playerName" maxlength="20" autocomplete="nickname" placeholder="Your name" required><div class="dialog-actions"><button class="btn" type="submit">Save score ↗</button></div></form></dialog>
<script>
const wordBank="about after again air almost along always among answer around ask away back become begin best better between both build change city close come common country course day different early earth enough even every example eye face fact feel few find first follow form found friend general get give go good great group hand happen help high home house idea important interest keep kind know large last learn leave letter life light line little live long look made make man many mean measure might move much must name near need never new next number often once open order other own part people place point right same say sentence set should show since small sound spell start state still story study take tell things think through time together turn under until use very want water way well while word work world write young quick brown fox jumps typing focus practice flow keyboard race speed calm steady bright clever forest river music moment simple smooth spark travel wonder fresh kind patient brave create gentle vivid morning night dream cloud meadow garden mountain ocean silent story easy light".split(" ");
function randomPassage(){const count=64;const words=Array.from({length:count},()=>wordBank[Math.floor(Math.random()*wordBank.length)]);return words.map((word,i)=>{if(i===0)return word[0].toUpperCase()+word.slice(1);if(i>0&&i%12===0)return word+',';return word}).join(' ')+'.'}
const SCORE_KEY='type-race-solo-leaderboard-v1';let passage='',started=false,finished=false,timer=null,seconds=60,typedCount=0,correctCount=0,pendingScore=null;
const $=id=>document.getElementById(id);const lanes=$('lanes'),box=$('typebox');
function carSvg(){return '<svg viewBox="0 0 32 20" fill="none"><path d="M4 13.5 7 7h14l5 4.2 3 1.1v4.2H4z" fill="currentColor" opacity=".92"/><path d="m9 7 2-3h8l3 3" stroke="currentColor" stroke-width="1.5"/><circle cx="10" cy="17" r="2" fill="#141610"/><circle cx="24" cy="17" r="2" fill="#141610"/></svg>'}
function buildLanes(){lanes.innerHTML='';const lane=document.createElement('div');lane.className='lane you';lane.innerHTML=`<span class="lane-name">YOU</span><div class="car" style="--car:#c5f36b;color:#c5f36b;--pos:0%">${carSvg()}</div>`;lanes.appendChild(lane)}
function drawQuote(){const pos=box.value.length;let html='';for(let i=0;i<passage.length;i++){let c=passage[i];if(i<pos){html+=`<span class="${box.value[i]===c?'typed':'wrong'}">${esc(c)}</span>`}else if(i===pos){html+=`<span class="current">${esc(c)}</span>`}else html+=esc(c)}$('quote').innerHTML=html;const cur=$('quote').querySelector('.current');if(cur&&pos>0&&pos>80)cur.scrollIntoView({block:'nearest',behavior:'smooth'})}
function esc(c){return c==='\n'?'<br>':c.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function start(){if(started)return;started=true;timer=setInterval(()=>{seconds--;updateStats();if(seconds<=0)endRace()},1000)}
function updateStats(){typedCount=box.value.length;correctCount=0;for(let i=0;i<typedCount;i++)if(box.value[i]===passage[i])correctCount++;const elapsed=Math.max(1,(60-seconds));const wpm=Math.round((correctCount/5)/(elapsed/60));const acc=typedCount?Math.round(correctCount/typedCount*100):100;$('wpm').innerHTML=`${wpm} <small>WPM</small>`;$('accuracy').innerHTML=`${acc}<small>%</small>`;$('time').innerHTML=`${seconds}<small>s</small>`;const progress=Math.min(95,typedCount/passage.length*100);document.querySelector('.lane.you .car').style.setProperty('--pos',progress+'%')}
function beginRace(){passage=randomPassage();seconds=60;started=false;finished=false;clearInterval(timer);box.value='';box.disabled=false;box.placeholder='Click here and start typing to join the race…';$('wpm').innerHTML='0 <small>WPM</small>';$('accuracy').innerHTML='100<small>%</small>';$('time').innerHTML='60<small>s</small>';document.querySelectorAll('.car').forEach(c=>c.style.setProperty('--pos','0%'));drawQuote();box.focus()}
function endRace(){clearInterval(timer);finished=true;started=false;seconds=Math.max(0,seconds);box.disabled=true;const wpm=Math.round((correctCount/5)/Math.max(1,(60-seconds)/60));const acc=typedCount?Math.round(correctCount/typedCount*100):100;pendingScore={wpm,acc};$('scoreSummary').textContent=`${wpm} WPM · ${acc}% accuracy`;$('nameDialog').showModal();$('playerName').focus()}
function readScores(){try{return JSON.parse(localStorage.getItem(SCORE_KEY)||'[]')}catch{return []}}
function updateLeaderboard(){const arr=readScores().sort((a,b)=>b.wpm-a.wpm||b.accuracy-a.accuracy).slice(0,10);$('leaderRows').innerHTML=arr.length?arr.map((r,i)=>`<div class="leader-row"><span class="rank ${i===0?'gold':''}">${String(i+1).padStart(2,'0')}</span><div class="person"><div class="mini-avatar">${esc((r.name||'?').trim().slice(0,2).toUpperCase())}</div><span class="person-name">${esc(r.name)}</span></div><span class="wpm">${r.wpm} wpm</span><span class="accuracy">${r.accuracy}% acc</span></div>`).join(''):'<div class="sub">Finish a run to claim the first spot.</div>';const best=arr[0];$('personalBest').textContent=best?`${Math.max(...arr.map(s=>s.wpm))} WPM`:'—'}
function renderRecent(){const items=readScores().sort((a,b)=>b.created-a.created).slice(0,3);$('recent').innerHTML=items.length?items.map(x=>`<div class="recent-item"><div class="recent-left"><div class="result-icon">↗</div><div class="result-text"><strong>Solo run · ${esc(x.name)}</strong><small>${new Date(x.created).toLocaleDateString()} · 60 sec</small></div></div><div class="result-score">${x.wpm} <span style="color:#777d73">wpm</span></div></div>`).join(''):'<div class="sub">Your completed runs will show up here.</div>'}
function saveScore(name){const score={name,wpm:pendingScore.wpm,accuracy:pendingScore.acc,created:Date.now()};const scores=readScores();scores.push(score);localStorage.setItem(SCORE_KEY,JSON.stringify(scores));$('playerLabel').textContent=name;$('profileAvatar').textContent=name.trim().slice(0,1).toUpperCase();updateLeaderboard();renderRecent();$('nameDialog').close();showToast(`Score saved · ${score.wpm} WPM`);pendingScore=null}
function showToast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3000)}
box.addEventListener('input',()=>{if(finished)return;if(!started&&box.value.length)start();drawQuote();updateStats();if(box.value.length>=passage.length)endRace()});$('restart').addEventListener('click',beginRace);document.addEventListener('keydown',e=>{if(e.key==='Tab'&&document.activeElement===box){e.preventDefault();box.dataset.tab='1'}else if(e.key==='Enter'&&box.dataset.tab==='1'){e.preventDefault();box.dataset.tab='';beginRace()}});$('nameDialog').addEventListener('cancel',e=>e.preventDefault());$('scoreForm').addEventListener('submit',e=>{e.preventDefault();if(!pendingScore)return;const name=$('playerName').value.trim();if(name)saveScore(name)});document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
buildLanes();updateLeaderboard(0,0);renderRecent();beginRace();
</script></body></html>"""


class TypingRaceHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path not in ("/", "/index.html"):
            self.send_error(404, "Not found")
            return
        body = PAGE.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)


if __name__ == "__main__":
    server = ThreadingHTTPServer(("127.0.0.1", 8000), TypingRaceHandler)
    print("type//race is running at http://127.0.0.1:8000")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nServer stopped.")
        server.server_close()
